-- liquibase formatted sql

-- changeset popova:1


CREATE TABLE users (
	id int8 NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	login varchar(255) NOT NULL,
	"password" varchar(255) NULL,
	phone varchar(255) NULL,
	"role" int4 NULL,
	image_id int8 NULL,
	CONSTRAINT login_unique UNIQUE (login),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


ALTER TABLE users ADD CONSTRAINT fk_users_image
FOREIGN KEY (image_id) REFERENCES image_entity(id);
-- changeset popova:2
CREATE TABLE ads (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	descriptions varchar(255) NULL,
	price int4 NULL,
	title varchar(255) NULL,
	image_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT ads_pkey PRIMARY KEY (id)
);

-- public.ads внешние включи

ALTER TABLE public.ads ADD CONSTRAINT fk_ads_image
 FOREIGN KEY (image_id) REFERENCES public.image_entity(id);
ALTER TABLE public.ads ADD CONSTRAINT fk_ads_users
FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- changeset potapov:1
CREATE TABLE comment (
	id int4 NOT NULL,
	created_at timestamp NULL,
	text varchar(255) NULL,
	ads_id int8 NULL,
	user_entity_id int8 NULL,
	CONSTRAINT comment_pkey PRIMARY KEY (id)
);


-- public."comment" внешние включи

ALTER TABLE comment ADD CONSTRAINT fk_comment_users
 FOREIGN KEY (user_entity_id) REFERENCES public.users(id);
ALTER TABLE comment ADD CONSTRAINT fk_comment_ads
FOREIGN KEY (ads_id) REFERENCES public.ads(id) ON DELETE CASCADE;


-- changeset potapov:2
CREATE TABLE image_entity (
	id int8 NOT NULL,
	data oid NULL,
	file_path varchar(255) NULL,
	file_size int8 NOT NULL,
	media_type varchar(255) NULL,

	CONSTRAINT image_entity_pkey PRIMARY KEY (id)
);